# Generated by Django 5.1.1 on 2024-10-10 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fatografia',
            new_name='Fotografia',
        ),
    ]
