# Generated by Django 5.1.1 on 2024-10-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_fatografia_fotografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'Nebulosa'), ('GALAXIA', 'Galaxia'), ('PLANETA', 'Planeta'), ('ESTRELA', 'Estrela')], default='', max_length=150),
        ),
    ]
