# Generated by Django 5.1.1 on 2024-10-24 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_fotografia_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data_fotografia',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
